### ISSUE TITLE
Fix camel case for native names

### ISSUE THREAD

**Issue by ivanjaros** [emvi/iso-639-1#1]
Looks like this is the only iso 639 library with native names. So tanks for that. But I have noticed there are mixed cases for these - often they start with lower case instead of camel case. This should be fixed and made uniform with English names.

**Comment by Kugelschieber** [comment]
Hi! Thank you for reporting, I'll take a look :+1:

**Comment by Kugelschieber** [comment]
Not really sure if we should change them. They are as listed on Wikipedia:

https://de.wikipedia.org/wiki/Liste_der_ISO-639-1-Codes

**Comment by ivanjaros** [comment]
Ignore that, it's not accurate whatsoever.
There are camel-casing libraries but for only the first character you could run it through:
```
r := []rune(s)
r[0] = unicode.ToUpper(r[0])
s := string(r)
```

this seems to have better list https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code

**Comment by Kugelschieber** [comment]
Done!

https://github.com/emvi/iso-639-1/releases/tag/v1.1.0
